fpmail:
    image: fpmail:latest
    restart: always
    environment:
      FPMAIL_OUT_DMS: "172.16.120.14"
    volumes:
      - /etc/fetchmail-docker/fetchmail:/data/fetchmailrc
      - /etc/fetchmail-docker/procmail:/data/procmailrc
      - /etc/fetchmail-docker/Mail:/data/mail
    ports:
      - 993:993
      - 10128:10128